#!/usr/bin/env bash
# This script pings an IP address and displays the results.

# Check if an IP address is provided as an argument
if [ -z "$1" ]; then
  echo "Usage: $0 {IP_ADDRESS}"
  exit 1
fi

# Ping the IP address 5 times
echo "PING $1"
ping -c 5 "$1"
