#!/bin/bash
#manages the script manage_my_process

# Function to start the process
start_process() {
    ./manage_my_process &
    echo $! > /var/run/my_process.pid
    echo "manage_my_process started"
}

# Function to stop the process
stop_process() {
    if [ -e "/var/run/my_process.pid" ]; then
        kill -TERM $(cat /var/run/my_process.pid)
        rm /var/run/my_process.pid
        echo "manage_my_process stopped"
    else
        echo "No running process found"
    fi
}

# Function to restart the process
restart_process() {
    stop_process
    start_process
    echo "manage_my_process restarted"
}

# Main script logic
case $1 in
    start)
        start_process
        ;;
    stop)
        stop_process
        ;;
    restart)
        restart_process
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        ;;
esac
