#!/usr/bin/env bash
# This script stops the process created by 4-to_infinity_and_beyond
pid=$(pgrep -f "4-to_infinity_and_beyond")
if [ -n "$pid" ]; then
  echo "Stopping process $pid"
  kill $pid
else
  echo "Process not found"
fi
