#!/usr/bin/env bash
# This script configures Nginx to run as the nginx user and listen on port 8080 in 7 lines or less

sed -i 's/user www-data/user nginx/' /etc/nginx/nginx.conf
service nginx restart
